### ISSUE TITLE
walletconnect package depends on React

### ISSUE THREAD

**Issue by arrudagates** [paritytech/polkadot-onboard#145]
The latest update introduces `@walletconnect/modal` as a dependency for `@polkadot-onboard/wallet-connect`, which is not framework agnostic and instead is a React implementation of the modal. My suggestion is that the wallet-connect package should remain framework agnostic and also modal agnostic by leaving the modal implementation up to the library user.

**Comment by hamidra** [comment]
This is in the wallet-modal core. I'd suggest opening an issue in their repo. Seems in the new version the modal has dependency on React.

```
├─┬ @polkadot-onboard/wallet-connect@1.1.0 -> ./packages/wallet-connect
│ └─┬ @walletconnect/modal@2.6.2
│   └─┬ @walletconnect/modal-core@2.6.2
│     └─┬ valtio@1.11.2
│       ├── react@18.2.0 deduped
│       └─┬ use-sync-external-store@1.2.0
│         └── react@18.2.0 deduped
```
