### ISSUE TITLE
Modules not found error

### ISSUE THREAD

**Issue by impelcrypto** [paritytech/polkadot-onboard#60]
It seems like installing dependencies are not working on both `react-headless` and `react-next` examples. I can't find `node_modules` folder after running `yarn install` or `npm run install`.

OS: MAC (M1)
Node: v18.16.0

![image](https://github.com/paritytech/polkadot-onboard/assets/92044428/dbc349d2-fddb-4f16-9dad-2d018ec8c2cb)

![image](https://github.com/paritytech/polkadot-onboard/assets/92044428/91b50c76-f285-470d-aec7-537d109102b2)

**Comment by hamidra** [comment]
I believe you run the yarn install from project's root directory.

You would need to switch to example directory and install the dependencies from there
```bash
cd ./examples/react-next
yarn install
```

or if you want to run from project root try:
```bash
yarn install:workspace

yarn start:react-next
# or
yarn start:react-headless
```

pls try and let us know if none of these helps.

**Comment by impelcrypto** [comment]
> cd ./examples/react-next
yarn install

This is exactly what I did.

**Comment by impelcrypto** [comment]
By the way, there is a installing error like this:

![image](https://github.com/paritytech/polkadot-onboard/assets/92044428/76606f3d-98df-4426-ad50-64fcb2733f93)

**Comment by hamidra** [comment]
I see you revert the version back to classic.
```bash
yarn set version classic
```

The repo is set for yarn v3
set you yarn version to yarn v3:
```bash
> yarn set version berry
> yarn install
```
