### ISSUE TITLE
When an extension wallet has eth accounts the lib throws error.

### ISSUE THREAD

**Issue by hamidra** [paritytech/polkadot-onboard#97]

**Comment by Tbaut** [comment]
FYI I had similar issues in my Dapp when I used encode/decode from pjs utils-crypto and it wasn't wrapped in a `try` `catch`. I searched the code but it couldn't find any occurrence, so I guess this happens with other lib a well.

**Comment by hamidra** [comment]
This should be handled by the downstream packages and apps since this library is meant to be unopinionated. 
The specific App should check if the injected accounts that they get by calling .getAccount() are available to their substrate chains and filter them based on the exposed type 'ed25519 | sr25519'
